version: '3'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=varta
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/varta
      - JWT_SECRET_KEY=production_jwt_secret_key
      - SECRET_KEY=production_secret_key
      - CORS_ALLOW_ORIGIN=http://localhost:5000
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: >
      bash -c "flask db upgrade && 
              gunicorn --bind 0.0.0.0:8080 run:app"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8080/api
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
