version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: varta-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: varta
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: varta-backend
    environment:
      NODE_ENV: production
      PORT: 8080
      JWT_SECRET: varta_jwt_secret_key_production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: varta
      DB_USER: postgres
      DB_PASSWORD: postgres
      CORS_ALLOW_ORIGIN: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: varta-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8080

volumes:
  postgres_data:
