runtime: python310

service: backend

entrypoint: gunicorn -b :$PORT run:app

env_variables:
  DATABASE_URL: "sqlite:///tmp/varta.db"
  JWT_SECRET_KEY: "production_jwt_secret_key"
  SECRET_KEY: "production_secret_key"
  CORS_ALLOW_ORIGIN: "*"

handlers:
- url: /.*
  script: auto

instance_class: F2
