runtime: python310

service: backend

entrypoint: gunicorn -b :$PORT run:app

env_variables:
  DATABASE_URL: "postgresql+psycopg2://postgres:postgres@localhost/varta"
  JWT_SECRET_KEY: "production_jwt_secret_key"
  SECRET_KEY: "production_secret_key"
  CORS_ALLOW_ORIGIN: "https://frontend-dot-varta-455515.uc.r.appspot.com"

handlers:
- url: /.*
  script: auto

instance_class: F2
