runtime: nodejs20

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  JWT_SECRET: "varta_jwt_secret_key_production"
  DB_HOST: "/cloudsql/varta-455515:us-central1:varta-db"
  DB_PORT: "5432"
  DB_NAME: "varta"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"

handlers:
  - url: /api/auth/register
    script: auto
    secure: always
    http_headers:
      Access-Control-Allow-Origin: https://frontend-dot-varta-455515.uc.r.appspot.com
      Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
      Access-Control-Allow-Headers: Content-Type, Authorization
      Access-Control-Allow-Credentials: 'true'
  
  - url: /api/.*
    script: auto
    secure: always
    http_headers:
      Access-Control-Allow-Origin: https://frontend-dot-varta-455515.uc.r.appspot.com
      Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
      Access-Control-Allow-Headers: Content-Type, Authorization
      Access-Control-Allow-Credentials: 'true'
  
  - url: /.*
    script: auto
    secure: always

beta_settings:
  cloud_sql_instances: "varta-455515:us-central1:varta-db"
